name: Realease
on:
  push:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build -t rubblestech3400/reactive:app .
    - run: echo "${{secrets.RUBBLES_TECH_PASSWORD}}" | docker login -u ${{secrets.DOCKER_HUB_USERNAME}} --password stdin
    - run: docker push rubblestech3400/reactive:app